name: first-workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Step 1"
  
  job2:
    runs-on: ubuntu-latest

    steps:
    - name: Cowsays
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'ship ship ship!'
        color: 'magenta'